// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzPGNpu8Zi7W_mdCYlAPCWcj8YEX7OOI',
    appId: '1:912337377390:web:46ab0f698264a170d42e7f',
    messagingSenderId: '912337377390',
    projectId: 'green-5bf89',
    authDomain: 'green-5bf89.firebaseapp.com',
    storageBucket: 'green-5bf89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0CMu2sZa7i0YCgtNXWk5rBr1_Dq2OKeg',
    appId: '1:912337377390:android:f8cf5031ecdf30c0d42e7f',
    messagingSenderId: '912337377390',
    projectId: 'green-5bf89',
    storageBucket: 'green-5bf89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjOCAGocT5wEW4lSX1HOD-Xe0E42dSXiM',
    appId: '1:912337377390:ios:f1ea29f4baab4d09d42e7f',
    messagingSenderId: '912337377390',
    projectId: 'green-5bf89',
    storageBucket: 'green-5bf89.appspot.com',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjOCAGocT5wEW4lSX1HOD-Xe0E42dSXiM',
    appId: '1:912337377390:ios:3b15c91b10ae377bd42e7f',
    messagingSenderId: '912337377390',
    projectId: 'green-5bf89',
    storageBucket: 'green-5bf89.appspot.com',
    iosBundleId: 'com.example.green.RunnerTests',
  );
}
